language: android
dist: trusty
jdk: oraclejdk8

env:
  global:
    # Some reusable vars for use here
    - ANDROID_API_LEVEL=30
    - EMULATOR_API_LEVEL=22
    - ANDROID_BUILD_TOOLS_VERSION=30.0.3
    - ANDROID_ABI=armeabi-v7a

android:
  components:
    # Use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # To use specific build-tool versions uncomment below
    #- build-tools-30.0.3    

    # The SDK version used to compile your project
    - android-${ANDROID_API_LEVEL}
    - android-${EMULATOR_API_LEVEL} # used for emulator

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-${ANDROID_API_LEVEL}
    - extra-android-support

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-${EMULATOR_API_LEVEL}

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  # Things to do before installation
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-${ANDROID_API_LEVEL}"
  - yes | sdkmanager "build-tools;${ANDROID_BUILD_TOOLS_VERSION}"
  - chmod +x gradlew

before_script:
  # Create and start emulator (used to run automated tests)
  - android list targets
  - echo no | android create avd --force -n test -t android-${EMULATOR_API_LEVEL} --abi ${ANDROID_ABI}
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

script:
  # Compile and run instrumented tests on the emulator
  - ./gradlew connectedAndroidTest

notifications:
  # Change the slack key below to the one given to match your team's channel
  slack: csc2007-ict2105:FwrAtWsnZAIxtKInBFeBv7zW # test channel